AZURE_OPENAI_ENDPOINT = "https://cursillogenai.openai.azure.com/"
AZURE_OPENAI_KEY = "9c04b423bfa64c82a178f71365d15094"
AZURE_DEPLOYMENT_NAME = "gpt-4o-mini"
AZURE_ASSISTANT_ID = "asst_qfbMwWkM6TuToGNWfJOvuWOJ"
